### PR TITLE
Fix various modal & autocomplete UX issues

### LINKED ISSUE #750: Text Search: Enable modal close+search on key Enter
The text search modal on the map view currently only applies the search on modal close (either via close button or clicking outside). We should also enable a user to search by pressing Enter, closing the modal and applying the search.

### PR DESCRIPTION
**Pull request by rachelekm**
## Overview

1. Fixes all modal alignment so that centered on Safari and iOS

2. Fixes autocomplete UX bugs:
   - Dispatches text search on exiting modals vs explicitly clicking outside of input and then exiting modal
   - Prevents autocomplete dropdown suggestions from remaining open following selection or search between mobile map and list view displays. Broadly cleans up autocomplete dropdown open logic
   - Allows keyboard navigation to text search clear button Note: I still can't setup keyboard navigation for the dropdown options. The react-aria combobox component has a lot of internal logic that *should* setup navigation from the get-go but I think is getting thrown off since we're using it within modals  (under the hood it expects a popover ref for the dropdown) and that's overwriting my explicit keydown callbacks. I'm leaving this for now with our remaining budget and we have an issue open to address (#751 ) 

### Checklist

- [x] `fixup!` commits have been squashed
- [x] `CHANGELOG.md` updated with summary of features or fixes, following
      [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] `README.md` updated if necessary to reflect the changes
- [x] Run `./scripts/format` to lint, format, and fix the application source code.
- [x] CI passes after rebase

### Demo

Modals centered in Safari and iOS:
Screenshot 2025-10-30 at 10 48 25 AM

Text search UX cleanup:

https://github.com/user-attachments/assets/604af3a0-6570-40fa-a807-f36c1135d1f0

## Testing Instructions

 * `scripts/server` and login
 * On mobile in the map display page, open up the text seach modal
 * Add some text input for a fuzzy search and exit the search modal
 * Confirm search performs as expected and navigate to list display
 * Confirm text search updated in list display search input and no dropdown is open
 * Clear text search and confirm no regressions resetting that filter
 * Input text search and make a neighborhood selection
 * Confirm the dropdown closes and the search performs as expected
 * Navigate to the map display and open the search modal
 * Confirm the dropdown is not open
 * Confirm no regressions with text search on desktop view
 * Open the app in a Safari browser
 * Confirm modals are centered as expected, specifically with login input modal, neighborhood details, and the search modal
 * Open the app in a Firefox browswer
 * Open responsive design mode and select different devices, specifically various iOS devices
 * Confirm modals are centered as expected in each device type

Resolves #750 #752 #757

### CODE REVIEW

File: src/frontend/src/components/base/Autocomplete/Autocomplete.tsx [hunk 1]
```diff
@@ -130,40 +130,51 @@ export function Autocomplete({
...
                             variant="outline"
                             size="small"
+                            ref={clearButtonRef}
                             leftIcon={
                                 <TimesIcon className="h-5 w-5 font-ligth fill-black" />
                             }
                             className="h-7 w-7 py-2 px-3 self-center mr-3"
                             aria-label="Clear search"
+                            onKeyDown={e => {
+                                if (e.key === "Enter") {
```
Comment (aaronxsu) [inline src/frontend/src/components/base/Autocomplete/Autocomplete.tsx]: I don't exactly recall, but I do wonder if these key strings are the same across different desktop OS.

**Review by aaronxsu — APPROVED** [review]
Tested and worked as advertised!

I noticed the following style thing, which we might consider fixing if time permits. In mobile neighborhood list view, the section below the text search seems to be pushed down when there are text search suggestions in the dropdown.

https://github.com/user-attachments/assets/dba055e0-bb86-41f8-8efe-301a77cb3fb3

File: src/frontend/src/components/base/Autocomplete/Autocomplete.tsx (hunk 1 above)
Comment (rachelekm) [reply src/frontend/src/components/base/Autocomplete/Autocomplete.tsx]: Oh great point, it might be worth just taking these onKeyDown props out before merge. It only partially solves #751 and is likely to cause more confusion to have them exist than not, from a development side and also if it's working differently across devices.

Comment (aaronxsu) [reply src/frontend/src/components/base/Autocomplete/Autocomplete.tsx]: Sounds like a good plan to me

**Comment by rachelekm** [comment]
> I noticed the following style thing, which we might consider fixing if time permits. In mobile neighborhood list view, the section below the text search seems to be pushed down when there are text search suggestions in the dropdown.

I saw this as well! tl;dr I'm struggling to work with this react-aria component and could see even a small style tweak spiraling. I even think it'd be better to have a larger refactor for it down that road vs continue to hack at it.

I'm pretty sure that style bug is because that dropdown isn't in an overlay or popover. I think this might be the same underlying cause preventing out-of-the-box keyboard navigation for this component. The initial react-spectrum `Autocomplete` component we were using did not have the ability to pass in props to allow fuzzy search. It's built with the the react-aria component `Combobox` under the hood (which does allow this customization) so I implemented that directly in #743. However, `Combobox` state expects references to a `Popover` component and a `Listbox` component for opening a dropdown and selecting options. I tried out quickly swapping those components in place of the `SearchField` and `Menu` (as well as applying the expected props from `Combobox` state to the component in place since we can [also import the context states](https://react-spectrum.adobe.com/react-aria/ComboBox.html#custom-children)) but then this caused some strange UI side effects for me like the inability to click on anything on that page. I think it's because of some inherit state their `Popover` component might have that we might need to work around, especially from within another modal. One quick alternative could be adding in the [Autocomplete component from HeroUI. ](https://www.heroui.com/docs/components/autocomplete)That lib is react-aria under-the-hood (and I'm pretty sure they also created tailwind variants?) and allows individual installation of components. But I'll add these thoughts into a future tech-debt issue.

**Comment by aaronxsu** [comment]
Got it. Thanks for expanding on those trial and errors. In this case, I'da say this is a trade-off for us to deal with in a tech debt issue, as you suggested. For the sake of time, let's keep the existing implementation then!

**Comment by rachelekm** [comment]
Thanks, @aaronxsu! I dropped the `onKeyDown` props in the latest rebase and added a changelog entry. I'll merge on successful CI build.
