### PR TITLE
Fix neighborhood detail and wizard UX bugs

### LINKED ISSUE #747: Allow 0 input for bedroom count step
In the first user profile step, a 0 input value disables the "continue" button. This is a valid input entry, fix the logic in this step of the wizard to allow continuing for the value.

Image

### PR DESCRIPTION
**Pull request by rachelekm**
## Overview

PR to fix a variety of small UX bugs, including:
- Allows 0 bedroom input when editing user profile
- Neighborhood detail: fixes transit map styling to display mbta map layers at lower zooms
- Neighborhood detail: fixes bug preventing transit map and trip routes from correctly updating when selecting neighborhood feature from the map
- Neighborhood detail: Fixes slightly-off map bounds in mobile trip route maps
- Neighborhood detail: Prevents "too far" route accordion panels from opening and displaying invalid route
- Neighborhood detail: Supports transit directions by ferry
- Fixes break line for trip length range indicator
- Prevents top 10 tour instructions from appearing over neighborhood details modal when refreshing page

### Checklist

- [x] `fixup!` commits have been squashed
- [x] `CHANGELOG.md` updated with summary of features or fixes, following
      [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] `README.md` updated if necessary to reflect the changes
- [x] Run `./scripts/format` to lint, format, and fix the application source code.
- [x] CI passes after rebase

### Demo

https://github.com/user-attachments/assets/c4036cf8-9967-4ba4-8ae5-f912abfa7873

Fixed range line breaks:
Screenshot 2025-10-28 at 1 11 38 PM
Enabled "ferry" transit option in trip directions:
Screenshot 2025-10-28 at 1 12 05 PM

## Testing Instructions

 * Login and confirm top 10 tour instructions display as expected on discover map view
 * Open edit profile wizard and confirm can continue past 1st step when inputting a 0 value for bedroom
 * Confirm can't input a non-number value or negative number to room input
 * Save wizard and confirm no regressions
 * Select neighborhood from map and confirm transit map at top of details displays all transit layers
 * Close modal and select different neighborhood from map
 * Confirm all parts of neighborhood detail modal update, specifically: transit map bounds are fit to correct neighborhood bounds in top map and all trip routes have correct start/end points for new neighborhood selection
 * Open each trip accordion and confirm: 1. maps are not loaded until accordion is opened, 2. maps correctly fit bounds to each accordion item route
 * On desktop view, confirm no regressions displaying different routes on one map as different accordions are expanded
 * Confirm that longer commute time ranges display ellipses vs wrapping around in your trips section as well as in neighborhood preview cards
 * Back on mobile, refresh page while opened neighborhood detail modal and confirm top 10 tour instructions do not open on top of details modal
 * Close modal and confirm top 10 instructions display on map view
 * Add 700 boylston st destination and then select "Hull" neighborhood
 * Confirm this trip destination includes a ferry route leg and "HINGHAM" correctly displays in the map trip directions

Resolves #747 #748 #761 #759

### CODE REVIEW

File: src/frontend/src/components/base/Accordion/AccordionItem.tsx [hunk 1]
```diff
@@ -26,12 +27,20 @@ export const AccordionItem = ({
...
     const styles = accordionStyles({ overridePanelOpen: overridePanelOpen });
+    const [isLazyLoaded, setIsLazyLoaded] = useState(false);
 
     return (
-        <Disclosure id={props.id} className={styles.accordionItemWrapper()}>
+        <Disclosure
+            id={props.id}
+            className={styles.accordionItemWrapper()}
+            onExpandedChange={isExpanded =>
+                lazyLoad && isExpanded && !isLazyLoaded && setIsLazyLoaded(true)
```
Comment (aaronxsu) [inline src/frontend/src/components/base/Accordion/AccordionItem.tsx:44]: It took me a bit to figure out why we have both `lazyLoad` and `isLazyLoaded`, and also what they mean here in this line. It might be helpful to add some quick comments about them.

File: src/frontend/src/components/YourTrips/TripMap.tsx [hunk 2]
```diff
@@ -95,13 +100,18 @@ const TripMap = ({
...
+                            right: 50,
+                            left: 50,
+                        },
                     },
                 }}
                 onLoad={() => setLoaded(true)}
                 interactive={false}
                 // @ts-ignore
-                mapStyle={baseMapDetailStyle}
+                mapStyle={baseMapTripStyle}
```
Comment (aaronxsu) [inline src/frontend/src/components/YourTrips/TripMap.tsx:118]: It might be helpful to add a comment here how baseMapTripStyle differs from baseMapDetailStyle _or_ baseMapStyle, since it's such a dense file.

**Review by aaronxsu — APPROVED** [review]
Works smoothly as advertised. I left two small suggestions to add code comments.

Another thing I found is that the style of the safety range label can sometimes look like the following. If this can be reproduced on your end, it might worth taking a look

Image

Other than that, this is good to go.

File: src/frontend/src/components/YourTrips/TripMap.tsx (hunk 2 above)
Comment (rachelekm) [reply src/frontend/src/components/YourTrips/TripMap.tsx:118]: Added clarifying comment in [5aa0943](https://github.com/azavea/echo-locator/pull/762/commits/5aa0943b7f2b52255bd6b3a7deaff765a1f8af28)

File: src/frontend/src/components/base/Accordion/AccordionItem.tsx (hunk 1 above)
Comment (rachelekm) [reply src/frontend/src/components/base/Accordion/AccordionItem.tsx:44]: Added a clarifying comment in [41d58df](https://github.com/azavea/echo-locator/pull/762/commits/41d58df702770d5bf7ead7be807dfccad3087013)

**Comment by rachelekm** [comment]
Thanks, @aaronxsu! I was able to reproduce the ranges falling out of alignment and added a quick fix as part of [d625183](https://github.com/azavea/echo-locator/pull/762/commits/d625183ce3600e42c8f04c250b7e13ccfe0dbfdb).  I also added clarifying comments to the two snippets that needed more context. I added a changelog entry and will merge in on succesful CI
